# Use the official Nginx image from the Docker Hub
FROM nginx:latest

# Copy custom Nginx configuration file into the container
COPY ./nginx.conf /etc/nginx/nginx.conf

# Expose port 80 to make the service accessible
EXPOSE 80
