# name: CI Pipeline

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   lint_and_test:
#     name: Lint and Test
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
        
#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.12'
        
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
#           pip install pytest-django
          
#       - name: Run black
#         run: black --check .
        
#       - name: Run tests
#         run: |
#           pytest tests/test_urls.py

#   build_and_push:
#     name: Build and Push Docker Image
#     runs-on: ubuntu-latest
#     needs: lint_and_test
#     if: success()
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
  
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
  
#       - name: Cache Docker layers
#         uses: actions/cache@v2
#         with:
#           path: ~/.cache
#           key: ${{ runner.os }}-docker-${{ github.sha }}
  
#       - name: Build the Docker image
#         run: |
#           docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/todo-project:latest .
  
#       - name: Docker image build completed
#         run: echo "Docker image built successfully."

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Push Docker image to Docker Hub
#         run: |
#           docker push ${{ secrets.DOCKER_USERNAME }}/todo-project:latest
          
#       - name: Docker image pushed to Docker Hub
#         run: echo "Docker image pushed to Docker Hub successfully."
